package Model;

public enum OldDirection {
	NORTH_NORTH_WEST, NORTH, NORTH_NORTH_EAST,
	EAST_NORTH_EAST, EAST, EAST_SOUTH_EAST,
	SOUTH_SOUTH_EAST, SOUTH, SOUTH_SOUTH_WEST,
	WEST_SOUTH_WEST, WEST, WEST_NORTH_WEST,
	CENTER
}
